// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD_BWjZmRuVSDmVV7ype8hRlhx8Lks5pc',
    appId: '1:1003758869710:web:7d568a5417e27abddd049f',
    messagingSenderId: '1003758869710',
    projectId: 'descartebem',
    authDomain: 'descartebem.firebaseapp.com',
    databaseURL: 'https://descartebem-default-rtdb.firebaseio.com',
    storageBucket: 'descartebem.appspot.com',
    measurementId: 'G-26B9FTPK2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ZK2mfW3SRCngagcI320JCRucv0Q3cfA',
    appId: '1:1003758869710:android:fa6dda9413b331b5dd049f',
    messagingSenderId: '1003758869710',
    projectId: 'descartebem',
    databaseURL: 'https://descartebem-default-rtdb.firebaseio.com',
    storageBucket: 'descartebem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn4M29nxkRr4tHtFy-geWmgF3gExI7fUA',
    appId: '1:1003758869710:ios:9c2580197a403ee4dd049f',
    messagingSenderId: '1003758869710',
    projectId: 'descartebem',
    databaseURL: 'https://descartebem-default-rtdb.firebaseio.com',
    storageBucket: 'descartebem.appspot.com',
    iosBundleId: 'com.example.navigationrail2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn4M29nxkRr4tHtFy-geWmgF3gExI7fUA',
    appId: '1:1003758869710:ios:5714449655eae7c0dd049f',
    messagingSenderId: '1003758869710',
    projectId: 'descartebem',
    databaseURL: 'https://descartebem-default-rtdb.firebaseio.com',
    storageBucket: 'descartebem.appspot.com',
    iosBundleId: 'com.example.navigationrail2.RunnerTests',
  );
}
